[package]
name = "rust-code-executor-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
tokio = { version = "1.16.1", features = ["io-std", "process"] }
winapi = { version = "0.3.9", features = ["processthreadsapi", "minwindef", "winnt", "psapi"] }