name: Rust-CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      -
      name: Check build
        uses: actions-rs/cargo@v1
        with:
          command: check

  clippy:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      -
      name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          
  tests:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Tests
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DockerfileWithTests
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/rust_ces:latest
